import { CategoryTemplate } from "@ai-zayavki/shared";

// The 5 MVP categories from ТЗ п.4/п.6. Admins can edit these later through
// the admin panel (they live in Category.fields as JSON) — this file only
// seeds the initial rows.
export const CATEGORY_SEED_DATA: CategoryTemplate[] = [
  {
    slug: "gazelle",
    name: "Газель",
    icon: "truck",
    examples: ["Нужна газель перевезти вещи при переезде", "Нужно перевезти мебель"],
    fields: [
      {
        key: "addressFrom",
        label: "Адрес загрузки",
        type: "address",
        required: true,
        question: "Укажите адрес загрузки и адрес выгрузки.",
        combineGroup: "addresses",
      },
      {
        key: "addressTo",
        label: "Адрес выгрузки",
        type: "address",
        required: true,
        question: "Укажите адрес загрузки и адрес выгрузки.",
        combineGroup: "addresses",
      },
      {
        key: "date",
        label: "Дата",
        type: "date",
        required: true,
        question: "На какую дату нужна газель?",
      },
      {
        key: "time",
        label: "Время подачи",
        type: "time",
        required: true,
        question: "В какое время нужна машина?",
      },
      {
        key: "weightKg",
        label: "Вес груза",
        type: "number",
        unit: "кг",
        required: true,
        allowUnknown: true,
        question: "Какой примерный вес груза?",
      },
      {
        key: "volumeM3",
        label: "Объём груза",
        type: "number",
        unit: "м³",
        required: true,
        allowUnknown: true,
        question: "Какой объём груза (в кубах или на глаз)?",
      },
      {
        key: "needLoaders",
        label: "Нужны грузчики",
        type: "boolean",
        required: true,
        question: "Нужны ли грузчики для погрузки/разгрузки?",
      },
      {
        key: "photos",
        label: "Фотографии",
        type: "photo",
        required: false,
        question: "Прикрепите фото груза, если есть — так проще оценить объём.",
      },
    ],
  },
  {
    slug: "dump-truck",
    name: "Самосвал",
    icon: "truck",
    examples: ["Нужен самосвал вывезти грунт", "Требуется самосвал"],
    fields: [
      {
        key: "address",
        label: "Адрес",
        type: "address",
        required: true,
        question: "Укажите адрес, куда подать самосвал.",
      },
      {
        key: "cargoType",
        label: "Что везём",
        type: "enum",
        required: true,
        options: [
          { value: "soil", label: "Грунт" },
          { value: "sand", label: "Песок" },
          { value: "gravel", label: "Щебень" },
          { value: "construction_debris", label: "Строительный мусор" },
          { value: "other", label: "Другое" },
        ],
        question: "Что нужно перевезти — грунт, песок, щебень или строительный мусор?",
      },
      {
        key: "volumeM3",
        label: "Объём",
        type: "number",
        unit: "м³",
        required: true,
        allowUnknown: true,
        question: "Какой объём (в кубах или количество ходок)?",
      },
      {
        key: "date",
        label: "Дата",
        type: "date",
        required: true,
        question: "На какую дату нужен самосвал?",
        combineGroup: "when",
      },
      {
        key: "time",
        label: "Время подачи",
        type: "time",
        required: true,
        question: "В какое время подать машину?",
        combineGroup: "when",
      },
      {
        key: "photos",
        label: "Фотографии",
        type: "photo",
        required: false,
        question: "Прикрепите фото, если есть.",
      },
    ],
  },
  {
    slug: "crane-truck",
    name: "Манипулятор",
    icon: "crane",
    examples: [
      "Нужен манипулятор на завтра",
      "Завтра нужен манипулятор перевезти бытовку из Астаны в Косшы",
    ],
    fields: [
      {
        key: "addressFrom",
        label: "Адрес",
        type: "address",
        required: true,
        question: "Укажите адрес загрузки.",
        combineGroup: "addresses",
      },
      {
        key: "addressTo",
        label: "Адрес назначения",
        type: "address",
        required: true,
        question: "Укажите адрес, куда доставить груз.",
        combineGroup: "addresses",
      },
      {
        key: "weightTons",
        label: "Вес груза",
        type: "number",
        unit: "т",
        required: true,
        allowUnknown: true,
        question: "Какой примерный вес груза (в тоннах)?",
      },
      {
        key: "dimensions",
        label: "Размеры груза",
        type: "text",
        required: true,
        allowUnknown: true,
        question: "Какие размеры груза?",
      },
      {
        key: "date",
        label: "Дата",
        type: "date",
        required: true,
        question: "На какую дату нужен манипулятор?",
        combineGroup: "when",
      },
      {
        key: "time",
        label: "Время подачи",
        type: "time",
        required: true,
        question: "В какое время нужна машина?",
        combineGroup: "when",
      },
      {
        key: "photos",
        label: "Фотографии",
        type: "photo",
        required: false,
        question: "Прикрепите фото груза, если есть.",
      },
    ],
  },
  {
    slug: "crane",
    name: "Автокран",
    icon: "crane-lift",
    examples: ["Нужен кран поднять груз", "Нужен автокран для монтажа"],
    fields: [
      {
        key: "address",
        label: "Адрес объекта",
        type: "address",
        required: true,
        question: "Укажите адрес объекта, куда подать кран.",
      },
      {
        key: "taskType",
        label: "Вид работ",
        type: "enum",
        required: true,
        options: [
          { value: "lifting", label: "Подъём груза" },
          { value: "installation", label: "Монтаж конструкций" },
          { value: "dismantling", label: "Демонтаж" },
          { value: "other", label: "Другое" },
        ],
        question: "Какие нужны работы — подъём груза, монтаж, демонтаж?",
      },
      {
        key: "liftWeightTons",
        label: "Вес груза",
        type: "number",
        unit: "т",
        required: true,
        allowUnknown: true,
        question: "Какой примерный вес груза для подъёма (в тоннах)?",
      },
      {
        key: "liftHeightM",
        label: "Высота/вылет",
        type: "number",
        unit: "м",
        required: true,
        allowUnknown: true,
        question: "На какую высоту или вылет стрелы нужно поднять груз?",
      },
      {
        key: "date",
        label: "Дата",
        type: "date",
        required: true,
        question: "На какую дату нужен кран?",
        combineGroup: "when",
      },
      {
        key: "time",
        label: "Время подачи",
        type: "time",
        required: true,
        question: "В какое время нужен кран?",
        combineGroup: "when",
      },
      {
        key: "photos",
        label: "Фотографии",
        type: "photo",
        required: false,
        question: "Прикрепите фото объекта или груза, если есть.",
      },
    ],
  },
  {
    slug: "construction-waste",
    name: "Вывоз строительного мусора",
    icon: "trash",
    examples: ["Нужно вывезти строительный мусор"],
    fields: [
      {
        key: "address",
        label: "Адрес",
        type: "address",
        required: true,
        question: "Укажите адрес, откуда вывозить мусор.",
      },
      {
        key: "wasteType",
        label: "Тип мусора",
        type: "enum",
        required: true,
        options: [
          { value: "concrete", label: "Бетон" },
          { value: "brick", label: "Кирпич" },
          { value: "mixed", label: "Смешанный" },
          { value: "other", label: "Другое" },
        ],
        question: "Какой тип мусора нужно вывезти?",
      },
      {
        key: "volumeM3",
        label: "Объём",
        type: "number",
        unit: "м³",
        required: true,
        allowUnknown: true,
        question: "Какой примерный объём мусора?",
      },
      {
        key: "needLoaders",
        label: "Нужны грузчики",
        type: "boolean",
        required: true,
        question: "Нужны ли грузчики для погрузки?",
      },
      {
        key: "date",
        label: "Дата",
        type: "date",
        required: true,
        question: "На какую дату нужен вывоз?",
        combineGroup: "when",
      },
      {
        key: "time",
        label: "Время",
        type: "time",
        required: true,
        question: "В какое время удобно?",
        combineGroup: "when",
      },
      {
        key: "photos",
        label: "Фотографии",
        type: "photo",
        required: false,
        question: "Прикрепите фото мусора, если есть.",
      },
    ],
  },
  {
    slug: "loaders",
    name: "Грузчики",
    icon: "people",
    examples: ["Нужны грузчики"],
    fields: [
      {
        key: "address",
        label: "Адрес",
        type: "address",
        required: true,
        question: "Укажите адрес.",
      },
      {
        key: "workType",
        label: "Вид работы",
        type: "enum",
        required: true,
        options: [
          { value: "loading", label: "Погрузка" },
          { value: "unloading", label: "Разгрузка" },
          { value: "moving", label: "Переезд" },
          { value: "floor_lift", label: "Подъём на этаж" },
        ],
        question: "Какая нужна работа — погрузка, разгрузка, переезд или подъём на этаж?",
      },
      {
        key: "numberOfLoaders",
        label: "Количество грузчиков",
        type: "number",
        required: true,
        allowUnknown: true,
        question: "Сколько нужно грузчиков?",
      },
      {
        key: "floor",
        label: "Этаж",
        type: "number",
        required: false,
        allowUnknown: true,
        question: "Какой этаж и есть ли лифт?",
        combineGroup: "floor",
      },
      {
        key: "hasElevator",
        label: "Есть лифт",
        type: "boolean",
        required: false,
        question: "Есть ли лифт в здании?",
        combineGroup: "floor",
      },
      {
        key: "date",
        label: "Дата",
        type: "date",
        required: true,
        question: "На какую дату нужны грузчики?",
        combineGroup: "when",
      },
      {
        key: "time",
        label: "Время",
        type: "time",
        required: true,
        question: "К какому времени?",
        combineGroup: "when",
      },
    ],
  },
];
